<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1606910313652' stop='1606910324912'>
    <name>throw error message for username and password field - </name>
    <title>throw error message for username and password field - </title>
    <test-cases>
        <test-case start='1606910313653' status='failed' stop='1606910324911'>
            <name>Should throw error message for both Email Id/Phone Number and Password field</name>
            <title>Should throw error message for both Email Id/Phone Number and Password field</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-86.0.4240.198'/>
                <parameter kind='argument' name='browser' value='chrome-86.0.4240.198'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Expect  to have text
                
                Expected: "You have entered incorrect password."
                Received: undefined</message>
                <stack-trace>Error: Expect  to have text
                
                Expected: "You have entered incorrect password."
                Received: undefined
                    at Context.&lt;anonymous> (C:\Users\Atul Kumar\Desktop\CTI\test\pages\logincopy.page.js:88:48)
                    at Context.executeSync (C:\Users\Atul Kumar\Desktop\CTI\node_modules\@wdio\sync\build\index.js:25:22)
                    at C:\Users\Atul Kumar\Desktop\CTI\node_modules\@wdio\sync\build\index.js:46:68</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>